apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "expiry-hawk.fullname" . }}
  labels:
    {{- include "expiry-hawk.labels" . | nindent 4 }}
    app: kube-prometheus-stack-operator
    release: kps
spec:
  selector:
    matchLabels:
      {{- include "expiry-hawk.labels" . | nindent 6 }}
  endpoints:
    - port: http
      honorLabels: true
