{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "expiry-hawk.serviceAccountName" . }}
  labels:
    {{- include "expiry-hawk.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployment-sts-daemonset-reader
  labels:
    {{- include "expiry-hawk.labels" . | nindent 4 }}
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: deployment-sts-daemonset-reader-binding
  labels:
    {{- include "expiry-hawk.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: "ClusterRole"
  name: deployment-sts-daemonset-reader
subjects:
  - kind: ServiceAccount
    name: {{ include "expiry-hawk.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
